"use client";

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Scale } from "lucide-react";

const ARTICLES = [
  {
    number: 0,
    title: "Purpose",
    clauses: [
      "This Constitution defines a formal evaluation and decision-making framework for assessing the quality and trustworthiness of responses generated by an AI agent. All evaluation, adjudication, and reconstruction shall be performed solely on the given response, without introducing external information.",
    ],
  },
  {
    number: 1,
    title: "Scoring Framework",
    clauses: [
      "All evaluations shall be conducted using a dual-perspective scoring system consisting of Defense and Prosecutor assessments.",
      "Each Claim and the overall response shall be assigned scores from both perspectives.",
      "Trust shall be computed as: Trust = w1 \u00d7 Ability + w2 \u00d7 Integrity + w3 \u00d7 Benevolence.",
      {
        text: "The default weights shall be:",
        items: ["w1 = 0.4", "w2 = 0.4", "w3 = 0.2"],
      },
      "The weights may be adjusted depending on context, but must be explicitly defined prior to evaluation.",
    ],
  },
  {
    number: 2,
    title: "Scope of Evaluation",
    clauses: [
      {
        text: "The response shall be decomposed into the following units.",
        items: [
          "Claim (atomic factual or inferential statement)",
          "Evidence (supporting justification, if present)",
          "Source (reference or provenance, if present)",
          "Uncertainty (explicit expression of uncertainty or limitation)",
        ],
      },
      "All evaluation, scoring, and reconstruction shall be strictly limited to the information contained within the given response.",
    ],
  },
  {
    number: 3,
    title: "Information Quality Criteria",
    preamble:
      "Consistent with verifiable knowledge: 1 \u00b7 Partially consistent: 0.5 \u00b7 Not verifiable: 0 \u00b7 Factually incorrect: \u22121",
    clauses: [
      "Each Claim shall be evaluated along the following dimensions.",
      "Accuracy refers to consistency with verifiable knowledge.",
      "Completeness refers to coverage of essential information.",
      "Believability refers to logical coherence and explainability.",
      "Reputation refers to credibility of supporting sources or evidence.",
      "Any Claim with Accuracy \u2264 0 shall be considered a critical defect.",
      "Any Claim with Completeness \u2264 0.5 shall be considered insufficient.",
      "Any Claim with Believability \u2264 0 shall be considered logically invalid.",
      "Any Claim with Reputation = 0 shall be considered unsupported.",
    ],
  },
  {
    number: 4,
    title: "Trust Component Computation",
    clauses: [
      "Accuracy \u2208 {\u22121, 0, 0.5, 1}, Completeness \u2208 {0, 0.5, 1}, Believability \u2208 {0, 0.5, 1}, Reputation \u2208 {0, 0.5, 1}.",
      "Ability = 0.6 \u00d7 Accuracy + 0.4 \u00d7 Completeness.",
      "Integrity = 0.5 \u00d7 Believability + 0.5 \u00d7 Reputation.",
      "Benevolence = 0.4 \u00d7 max(Accuracy, 0) + 0.2 \u00d7 Completeness + 0.2 \u00d7 Believability + 0.2 \u00d7 Reputation.",
      "All computations shall be performed strictly using the defined measured values without introducing external criteria, heuristic adjustments, or qualitative interpretation.",
      "No external criteria or qualitative judgment beyond the measured values shall be used in computing Ability, Integrity, and Benevolence.",
    ],
  },
  {
    number: 5,
    title: "Decision Rules Based on Trust",
    clauses: [
      "Outcomes shall be determined based on the computed Trust score.",
      "If Trust < 0.5, the response shall be rejected and must not be used.",
      "If Trust \u2265 0.8, the response shall be accepted and used without modification.",
      "If 0.5 \u2264 Trust < 0.8, the response shall proceed to selective reconstruction under Article 6.",
    ],
  },
  {
    number: 6,
    title: "Selective Reconstruction and Integration",
    clauses: [
      "Selective reconstruction shall be applied to responses within the intermediate Trust range.",
      "If the Defense-side Trust \u2265 0.8, the Defense response shall be used without modification.",
      "If 0.5 \u2264 Defense-side Trust < 0.8, responses shall be integrated based on comparative evaluation between Defense and Prosecutor.",
      "If the Defense-side Trust is marginally acceptable but not sufficiently reliable, a re-evaluation process shall be recommended.",
      "Only Claims with relatively stronger evaluated quality shall be retained during integration.",
      "Claims identified as defective, misleading, unsupported, or risky shall be excluded.",
      "The reconstructed response shall be formed by selecting, filtering, and reorganizing retained Claims.",
      "No new Claims, facts, or external information may be introduced during reconstruction.",
      "All reconstructed outputs must be a subset or recombination of the original Claims.",
      "The semantic meaning of retained Claims shall not be altered during reconstruction.",
    ],
  },
  {
    number: 7,
    title: "Justification Requirement",
    clauses: [
      "All decisions and reconstructions shall include explicit justification.",
      {
        text: "The justification shall include:",
        items: [
          "Evaluation results of key Claims",
          "Comparison between Defense and Prosecutor assessments",
          "Identification of retained and discarded elements",
          "Explanation of the final Trust assessment",
        ],
      },
    ],
  },
  {
    number: 8,
    title: "Prohibited Actions",
    clauses: [
      {
        text: "The following actions are prohibited.",
        items: [
          "Introducing any information not present in the original response",
          "Generating new Claims or modifying existing Claims",
          "Supplementing missing information with external knowledge",
          "Altering the meaning of Claims during reconstruction",
          "Producing outputs without explicit justification",
        ],
      },
    ],
  },
  {
    number: 9,
    title: "Objective",
    clauses: [
      "Only information with justified trustworthiness shall be delivered to the user.",
      "Trust shall be proportional to underlying information quality, not to rhetorical persuasiveness.",
    ],
  },
];

type Clause = string | { text: string; items: string[] };

function ClauseBlock({
  clause,
  index,
}: {
  clause: Clause;
  index: number;
}) {
  if (typeof clause === "string") {
    return (
      <p className="text-foreground/75 leading-relaxed">
        <span className="text-burgundy/50 text-xs font-medium mr-2">
          Clause {index + 1}.
        </span>
        {clause}
      </p>
    );
  }

  return (
    <div>
      <p className="text-foreground/75 leading-relaxed">
        <span className="text-burgundy/50 text-xs font-medium mr-2">
          Clause {index + 1}.
        </span>
        {clause.text}
      </p>
      <ul className="mt-1.5 ml-6 space-y-1">
        {clause.items.map((item, i) => (
          <li key={i} className="text-foreground/65 leading-relaxed flex gap-2">
            <span className="text-burgundy/40 text-xs mt-0.5 shrink-0">
              {String.fromCharCode(105 + i)}.
            </span>
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}

export function ConstitutionDialog() {
  return (
    <Dialog>
      <DialogTrigger className="text-burgundy/65 hover:text-burgundy transition-colors duration-300 underline decoration-burgundy/25 underline-offset-2 hover:decoration-burgundy/50 cursor-pointer">
        Constitution
      </DialogTrigger>
      <DialogContent
        className="sm:max-w-2xl max-h-[85vh] p-0 border-burgundy/20 bg-[#ede6db] shadow-2xl shadow-burgundy/10"
        showCloseButton={false}
      >
        {/* Ornate header */}
        <DialogHeader className="px-8 pt-8 pb-0">
          <div className="flex flex-col items-center text-center">
            <Scale
              className="w-8 h-8 text-burgundy/30 mb-4"
              strokeWidth={1}
            />
            <div className="w-16 h-px bg-burgundy/15 mb-4" />
            <DialogTitle className="font-serif text-2xl tracking-[0.12em] text-burgundy font-medium">
              THE CONSTITUTION
            </DialogTitle>
            <p className="text-xs text-burgundy/40 tracking-[0.2em] uppercase mt-2 font-serif">
              AI Agent Trustworthiness Framework
            </p>
            <div className="w-16 h-px bg-burgundy/15 mt-4" />
          </div>
        </DialogHeader>

        {/* Scrollable articles */}
        <ScrollArea className="max-h-[60vh]">
          <div className="px-8 pb-8 pt-4 space-y-8">
            {ARTICLES.map((article) => (
              <section key={article.number}>
                {/* Article heading */}
                <div className="flex items-baseline gap-3 mb-3">
                  <span className="font-serif text-sm text-burgundy/40 tracking-wider shrink-0">
                    Art. {article.number}
                  </span>
                  <h3 className="font-serif text-base text-burgundy tracking-wide font-medium">
                    {article.title}
                  </h3>
                </div>

                {/* Decorative line under heading */}
                <div className="w-full h-px bg-burgundy/8 mb-3" />

                {/* Preamble (evaluation scale) */}
                {article.preamble && (
                  <div className="mb-3 px-4 py-2.5 rounded-lg bg-burgundy/[0.04] border border-burgundy/8">
                    <p className="text-xs text-burgundy/50 tracking-wide font-medium">
                      {article.preamble}
                    </p>
                  </div>
                )}

                {/* Clauses */}
                <div className="space-y-2.5 text-sm">
                  {article.clauses.map((clause, i) => (
                    <ClauseBlock key={i} clause={clause} index={i} />
                  ))}
                </div>
              </section>
            ))}

            {/* Closing ornament */}
            <div className="flex flex-col items-center pt-4">
              <div className="w-16 h-px bg-burgundy/15" />
              <p className="text-[10px] text-burgundy/25 tracking-[0.25em] uppercase mt-4 font-serif">
                Finis
              </p>
            </div>
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
